### create vocabulary

POST http://localhoost:8080/api/vocabularies HTTP/1.1
content-type: application/json

{
	"name": "SmarterVocabulary",
	"vocabularyUrl": "jar:file:vocabularies/smarter-vocabulary-1.0-SNAPSHOT-shaded.jar!/",
	"rootPackageName": "com.vocabularies.smarter"
}

### get vocabularies

GET http://localhoost:8080/api/vocabularies

### get single vocabulary

GET http://localhoost:8080/api/vocabularies/65662b357d16023212908e73

### create rule

POST http://localhoost:8080/api/rules HTTP/1.1
content-type: application/json

{
	"name": "rule and test v4",
	"vocabularies": [
		"65662b357d16023212908e73"
	],
	"condition": {
		"name": "ExpressionCardBlock",
		"vocabulary": "65662b357d16023212908e73",
		"params": [
			{
				"name": "IsTrueBlock",
				"vocabulary": "65662b357d16023212908e73",
				"params": []
			}
		]
	},
	"actions": [
		{
			"name": "TurnOffLedBlock",
			"vocabulary": "65662b357d16023212908e73",
			"params": []
		}
	]
}

### create rule 2

POST http://localhoost:8080/api/rules HTTP/1.1
content-type: application/json

{
	"name": "rule and test v4",
	"vocabularies": [
		"65662b357d16023212908e73"
	],
	"condition": {
		"name": "InsertedCardBlock",
		"vocabulary": "65662b357d16023212908e73",
		"params": [
			{
				"name": "IsNumberBlock",
				"vocabulary": "65662b357d16023212908e73",
				"params": []
			},
			{
				"name": "IsAnyBlock",
				"vocabulary": "65662b357d16023212908e73",
				"params": []
			},
			{
				"name": "Integer",
				"vocabulary": "65662b357d16023212908e73",
				"params": [],
				"value": 1
			}
		]
	},
	"actions": [
		{
			"name": "TurnOffLedBlock",
			"vocabulary": "65662b357d16023212908e73",
			"params": []
		}
	]
}

### get rules

GET http://localhoost:8080/api/rules

### delete rule

DELETE http://localhoost:8080/api/rules/65662f877d16023212908e75

### create task

POST http://localhoost:8080/api/tasks HTTP/1.1
content-type: application/json

{
	"name": "Task SmarterVocabulary v2",
	"vocabularies": [
		"6554ffe010da383f7fcdbf2d"
	]
}

### get tasks

GET http://localhoost:8080/api/tasks

### create rule of task

PUT http://localhoost:8080/api/tasks/6557fa98a688b03aaf95f730 HTTP/1.1
content-type: application/json

{
	"id": "6557fa98a688b03aaf95f730",
	"name": "Task SmarterVocabulary v2",
	"rules": ["6557fb59a688b03aaf95f731"]
}
