### create vocabulary

POST http://localhoost:8080/api/vocabularies HTTP/1.1
content-type: application/json

{
	"name": "SmarterVocabulary",
	"vocabularyUrl": "jar:file:vocabularies/smarter-vocabulary-1.0-SNAPSHOT-shaded.jar!/",
	"rootPackageName": "com.vocabularies.smarter"
}

### get vocabularies

GET http://localhoost:8080/api/vocabularies

### get single vocabulary

GET http://localhoost:8080/api/vocabularies/6554ffe010da383f7fcdbf2d

### create rule

POST http://localhoost:8080/api/rules HTTP/1.1
content-type: application/json

{
	"name": "rule 2",
	"condition": {
		"name": "OnLeftBlock",
		"vocabulary": "6554ffe010da383f7fcdbf2d",
		"params": [
			{
				"name": "IsNumberBlock",
				"vocabulary": "6554ffe010da383f7fcdbf2d",
				"params": []
			}
		]
	},
	"actions": [
		{
			"name": "HelloWorldBlock",
			"vocabulary": "6554ffe010da383f7fcdbf2d",
			"params": []
		}
	]
}

### get rules

GET http://localhoost:8080/api/rules

### create task

POST http://localhoost:8080/api/tasks HTTP/1.1
content-type: application/json

{
	"name": "Task SmarterVocabulary v2",
	"vocabularies": [
		"6554ffe010da383f7fcdbf2d"
	]
}

### get tasks

GET http://localhoost:8080/api/tasks

### create rule of task

PUT http://localhoost:8080/api/tasks/6557fa98a688b03aaf95f730 HTTP/1.1
content-type: application/json

{
	"id": "6557fa98a688b03aaf95f730",
	"name": "Task SmarterVocabulary v2",
	"rules": ["6557fb59a688b03aaf95f731"]
}
